var GAME_LEVELS = [
  [" xxx                                                                          xxx ",
   " x                                                                           o  x ",
   " x                                                        o                     x ",
   " x                                                        i                     x ",
   " x                                                        o         xx       o  x ",
   " x                                                                              x ",
   " x                                        xxx            xxx                xxx x ",
   " x                                                                              x ",
   " x                                  o                                           x ",
   " x                                                 xyyyx                        x ",
   " x                   i              o                                           x ",
   " x                                                         o   o   o   o   o    x ",
   " x                 xyyyx            o    xxxxx                                  x ",
   " x                 x   x                                                        x ",
   " x             xxxxx   x o        xxxxx                 xxxxxxxxxxxxxxxxxxxxxxxxx ",
   " x  @          x       x          x   x                 x                         ",
   " xxxxxxxxxxxxxxx       x   xxxxxxxx   xxxxxxxxxx        x                         ",
   "                       x   x                   x!!!!!!!!x                         ",
   "                       x!!!x                   x!!!!!!!!x                         ",
   "                       x!!!x                   xxxxxxxxxx                         ",
   "                       x!!!x                                                      ",
   "                       xxxxx                                                      ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  "],
  ["                               xxxxx                                v        v            ",
   "                               x!!!x                                                      ",
   "                               x!!!x                                                      ",
   "                               xxvxx                                                      ",   
   "                                                                                          ",
   "                                                                                          ",
   "                                                                                          ",
   "                                                                                          ",
   "                                                                                          ",
   "                                                                 o                   o    ",
   "                                                                                          ",
   "                                 o                               o                  xxx   ",
   "                                              i                                           ",
   "                             o  xxx          xxx                xxx                       ",
   "                                                                                          ",
   "                   xxx       o                                                          o ",
   "                                                                                          ",
   "                             o                                                         xxx",
   "                                                                    xxxx                  ",
   "                           xyyyx                                                          ",
   "                                                                                          ",
   "                                                                                       x  ",
   "        i                                                                         i       ",
   "       xxx                                                               xxx              ",
   "                                                                               o o o o    ",
   "                                                                                      |   ",
   "                                                                              xxxxxxxxx   ",
   "                                                                                          ",
   "   @                                                                                      ",
   " xxxxy                                                                                    ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                          ",
   "               xxxxxxxxxxx                                                                ",
   "     o                                                                                    ",
   "                                                                                          ",
   "     o                                                                                    ",
   "                                                     o                                    ",
   "   xxxxx                                                                                  ",
   "   x!!!x          o   o                              o                                    ",
   "   x!!!x        |   |   |                                                                 ",
   "   x!!!x       xxxxxxxxxxx                       xxxxxxxxx                                ",
   "  xxxvxxx                x=                      x       x                                ",
   "                         x     x     x     x     x       x                                ",
   "                         x!!!!!!!!!!!!!!!!!!!!!!!x       xx                               ",
   "                         xxxxxxxxxxxxxxxxxxxxxxxxx       x                        o       ",
   "                                                         x                                ",
   "                                                         x                        o       ",
   "          i                                              xx                               ",
   "       xxxxxyyx                                          x                       xxx      ",
   "       x                                     o           x                                ",
   "       x                                                 x                                ",
   "       x                                     o           xx                               ",
   "      xx                                                                                  ",
   "       x           o       o       o         o                                            ",
   "       x                                                                      i           ",
   "       x           x       x   |   x       xyyyxxxxxxxxxxxxxxxx       x      xxx          ",
   "      xx           x!!!!!!!!!!!!!!!!!!!!!!!x                                              ",
   "       x           xxxxxxxxxxxxxxxxxxxxxxxxx                                              ",
   "       x                                                                                  ",
   "       x                                                                                  ",
   "      xx                                                                                  ",
   "       x                                                                                  ",
   "       x                                                                                  ",
   "       x                                                                                  ",
   "      xx                                                                                  ",
   "       x                                                                                  ",
   "       x                                                                                  ",
   "  @    x                                                                                  ",
   " xxxxxxx                                                                                  ",],
  ["                                                              ",
   " xx    xx    xxxx    xx    xx                                 ",
   " xx    xx   xxxxxx   xx    xx                                 ",
   " xx    xx  xx    xx  xx    xx                                 ",
   "   xxxx    xx    xx  xx    xx                                 ",
   "    xx     xx    xx  xx    xx                                 ",
   "    xx      xxxxxx    xxxxxx                                  ",
   "    xx       xxxx      xxxx                                   ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   " yy       yy  yy  yyyy     yy                                 ",
   " yy       yy  yy  yy yy    yy                                 ",
   " yy       yy  yy  yy  yy   yy                                 ",
   " yy  yyy  yy  yy  yy   yy  yy                                 ",
   " yy yy yy yy  yy  yy    yy yy                                 ",
   " yyyy   yyyy  yy  yy     yyyy                                 ",
   "  yy     yy   yy  yy      yyy                                 ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",
   "                                                              ",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
